import { Value, View } from '@tweakpane/core';
import type { Rotation } from './Rotation.js';
import type { RotationInputGizmoViewConfig } from './RotationInputGizmoViewConfig.js';
export declare class RotationInputGizmoView implements View {
    readonly element: HTMLElement;
    readonly padElement: HTMLDivElement;
    readonly value: Value<Rotation>;
    readonly xLabel: SVGGElement;
    readonly yLabel: SVGGElement;
    readonly zLabel: SVGGElement;
    readonly xnLabel: SVGGElement;
    readonly ynLabel: SVGGElement;
    readonly znLabel: SVGGElement;
    private readonly mode_;
    private readonly svgElem_;
    private readonly axesElem_;
    private readonly labelsElem_;
    private readonly projector_;
    private readonly xAxis_;
    private readonly yAxis_;
    private readonly zAxis_;
    private readonly xnAxis_;
    private readonly ynAxis_;
    private readonly znAxis_;
    private readonly xArcB_;
    private readonly yArcB_;
    private readonly zArcB_;
    private readonly xArcBC_;
    private readonly yArcBC_;
    private readonly zArcBC_;
    private readonly xArcF_;
    private readonly yArcF_;
    private readonly zArcF_;
    private readonly xArcFC_;
    private readonly yArcFC_;
    private readonly zArcFC_;
    private readonly rArc_;
    private readonly rArcC_;
    get xArcBElement(): SVGPathElement;
    get yArcBElement(): SVGPathElement;
    get zArcBElement(): SVGPathElement;
    get xArcFElement(): SVGPathElement;
    get yArcFElement(): SVGPathElement;
    get zArcFElement(): SVGPathElement;
    get rArcElement(): SVGPathElement;
    constructor(doc: Document, config: RotationInputGizmoViewConfig);
    get allFocusableElements(): HTMLElement[];
    private update_;
    private onValueChange_;
    private onFoldableChange_;
    private onModeChange_;
}
