name: Publish gh-pages

on:
  push:
    branches:
      - release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install + Prepare
      run: yarn
    - name: Organize pages stuff
      run: |
        mkdir _site
        cp -r README.md LICENSE.txt package.json index.html dist _site
    - name: Upload Builds
      uses: actions/upload-pages-artifact@v2

  pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
    - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
